wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1657725537
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      4: 3.10.4
      5: 0.12.17
      8:
      - 3
      - 5
alpha:
  desc: null
  value: 1.05
architecture:
  desc: null
  value: ResNet
avg_mrgn_loss_type:
  desc: null
  value: '-'
batchsize_train:
  desc: null
  value: null
beta:
  desc: null
  value: 0
dataset:
  desc: null
  value: FMNIST
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.025
left_loss:
  desc: null
  value: linear
loss_type:
  desc: null
  value: avg-max
momentum:
  desc: null
  value: 0.9
n:
  desc: null
  value: 256
scheduler_gamma:
  desc: null
  value: 0.9
scheduler_step:
  desc: null
  value: 300
seed:
  desc: null
  value: 0
test:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0
